Custom schema errors (#18)
* Move legacy errors to its own template

* Update golang-basics example with custom errors

Based on https://github.com/webrpc/webrpc/compare/master...schema-v2

* Implement custom errors in Go templates

* Render errors dynamically

* Use latest webrpc

* Regenerate examples

* Simplify status code server logic

* Backward-compatibility flag: -legacyErrors=true

* Fix response body close error

* Update RPCError.Is() and send httpStatus

* Remove Errorf()

* Add 405 error, improve client/server errors

* Regenerate examples

* Support legacy errors by default

* Disable legacy errors by default

* Revert error payload changes for backward compatibility

* Fix template runtime error

template: main.go.tmpl:8:39: executing "main" at <eq .Opts.legacyErrors "true">: error calling eq: incompatible types for comparison

* Update to built-in webrpc errors

https://github.com/webrpc/webrpc/pull/196

* Improve test case

* Update to webrpc@v0.11.0-rc1

* Update to webrpc@v0.11.0-rc2

* Test against latest webrpc

* Regenerate examples

* Bump webrpc version for interoperability tests

* Remove interoperability tests in favor of webrpc/webrpc

See https://github.com/webrpc/webrpc/tree/master/tests.

No need to maintain this twice.

* Fix pointers per https://github.com/webrpc/webrpc/issues/127